import React from "react";

/**
 * Renders a self-hosted responsive image generated by scripts/fetch-airtable.mjs.
 * `image` is { src, srcSet, width, height }.
 */
function WorkImage({ image, alt = "artwork", sizes, loading = "lazy", ...rest }) {
  if (!image?.src) return null;
  return (
    <img
      alt={alt}
      src={image.src}
      srcSet={image.srcSet}
      sizes={sizes}
      width={image.width}
      height={image.height}
      loading={loading}
      decoding="async"
      {...rest}
    />
  );
}

export default WorkImage;
