import React from "react";
import { formatWorkAltText } from "./formatWorkDetails.jsx";

/**
 * Renders a self-hosted responsive image generated by scripts/fetch-airtable.mjs.
 * `image` is { src, srcSet, width, height }.
 * Pass `work` to auto-generate alt text from title, year, medium, and dimensions.
 */
function WorkImage({ image, work, alt, sizes, loading = "lazy", ...rest }) {
  if (!image?.src) return null;
  const altText = alt ?? (work ? formatWorkAltText(work) : "artwork");
  return (
    <img
      alt={altText}
      src={image.src}
      srcSet={image.srcSet}
      sizes={sizes}
      width={image.width}
      height={image.height}
      loading={loading}
      decoding="async"
      {...rest}
    />
  );
}

export default WorkImage;
